@startuml container_startup

Runtime -> Runtime: Check and Mount container
create Trampoline
Runtime -> Trampoline: Clone
create Init
Trampoline-> Init: Clone
Trampoline-> Runtime: Init PID
destroy Trampoline
Runtime -> Runtime: Wait for Trampoline exit
Init -> Init: Wait for run signal
Runtime -> Runtime: Configure cgroups
Runtime -> Init: Signal run
Runtime -> Runtime: Wait for execve
Init -> Init: Mount, Chroot, UID / GID,\ndrop privileges, file descriptors
create Container
Init -> Container: Clone Container
Init -> Init: Wait for container to exit (waitpid)
Container -> Container: Set seccomp filter
Container -> Runtime: Execve 
Container -> Container: Run container executable
Runtime -> Runtime: Continue operation
Container -> Init: Exit
destroy Container
Init -> Runtime: Exit
destroy Init

@enduml
