[package]
name = "seccomp-util"
version = "0.1.0"
authors = ["ESRLabs"]
edition = "2018"

[dependencies]
anyhow = "1.0"
assert_cmd = "2.0"
env_logger = "0.8.3"
itertools = "0.10.1"
northstar = { path = "../../northstar", features = ["npk", "runtime"] }
regex = "1.5"
serde_yaml = "0.8.21"
structopt = "0.3"