[package]
name = "seccomp-util"
version = "0.1.0"
authors = ["ESRLabs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.54"
clap = { version = "3.1.2", features = ["derive"] }
env_logger = "0.9.0"
itertools = "0.10.1"
northstar = { path = "../../northstar", features = ["seccomp"] }
regex = "1.5.4"
serde_yaml = "0.8.21"

[dev-dependencies]
assert_cmd = "2.0.4"
