[package]
name = "seccomp-util"
version = "0.1.0"
authors = ["ESRLabs"]
edition = "2018"

[dependencies]
anyhow = "1.0.44"
assert_cmd = "2.0.2"
env_logger = "0.9.0"
itertools = "0.10.1"
northstar = { path = "../../northstar", features = ["seccomp"] }
regex = "1.5.4"
serde_yaml = "0.8.21"
structopt = "0.3.25"
