[package]
name = "main"
version = "0.1.0"
authors = ["ESRLabs"]
edition = "2018"
default-run = "northstar"

[[bin]]
name = "northstar"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
log = "0.4.14"
nix = "0.20.0"
northstar = { path = "../northstar", features = ["runtime"] }
structopt = "0.3.21"
tokio = { version = "1.4", features = ["full"] }
toml = "0.5.8"

[target.'cfg(not(target_os = "android"))'.dependencies]
env_logger = "0.8.3"

[target.'cfg(target_os = "android")'.dependencies]
android-logd-logger = "0.1.3"

[features]
default = []
hello-world = ["northstar/hello-world"]