[package]
name = "redis"
version = "0.0.1"
authors = ["ESRLabs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
mini-redis = "0.4.1"
tokio = { version = "1.19.2", features = ["macros", "rt", "net", "signal"] }
