[package]
name = "nstar"
version = "0.4.2"
authors = ["ESRLabs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.12", features = ["derive"] }
clap_complete = "3.1.3"
futures = "0.3.21"
hex = "0.4.3"
humantime = "2.1.0"
itertools = "0.10.3"
northstar = { path = "../../northstar", features = ["api"], default-features = false }
prettytable-rs = "0.8.0"
schemars = "0.8.8"
serde_json = "1.0.80"
tokio = { version = "1.18.0", features = ["fs", "io-std", "io-util", "macros", "net", "rt", "time"] }
url = "2.2.2"
