[package]
name = "nstar"
version = "0.4.1"
authors = ["ESRLabs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.44"
clap = { version = "3.1.0", features = ["derive"] }
clap_complete = "3.1.0"
futures = "0.3.21"
itertools = "0.10.1"
northstar = { path = "../../northstar", features = ["api"], default-features = false }
prettytable-rs = "0.8.0"
schemars = "0.8.6"
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["fs", "io-std", "io-util", "macros", "net", "rt", "time"] }
url = "2.2.2"
