[package]
name = "nstar"
version = "0.4.2"
authors = ["ESRLabs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.15", features = ["derive"] }
clap_complete = "3.1.3"
futures = { version = "0.3.21", default-features = false }
hex = "0.4.3"
humantime = "2.1.0"
itertools = "0.10.3"
northstar = { path = "../../northstar", features = ["api"], default-features = false }
pin-project-lite = "0.2.9"
prettytable-rs = "0.8.0"
serde_json = "1.0.81"
tokio = { version = "1.18.1", features = ["fs", "io-std", "io-util", "macros", "net", "rt", "time"] }
tokio-util = "0.7.2"
url = "2.2.2"
