[package]
name = "nstar"
version = "0.4.0"
authors = ["ESRLabs"]
edition = "2021"

[dependencies]
anyhow = "1.0.44"
futures = "0.3.17"
itertools = "0.10.1"
northstar = { path = "../../northstar", features = ["api"], default-features = false }
prettytable-rs = "0.8.0"
serde_json = "1.0.68"
structopt = "0.3.25"
tokio = { version = "1.12.0", features = ["fs", "io-std", "io-util", "macros", "net", "rt", "time"] }
url = "2.2.2"
