[package]
name = "stress"
version = "0.1.0"
authors = ["ESRLabs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive"] }
env_logger = "0.9.0"
futures = { version = "0.3.21", default-features = false }
humantime = "2.1.0"
itertools = "0.10.3"
log = "0.4.17"
northstar = { path = "../../northstar", features = ["api"] }
rand = "0.8.5"
tokio = { version = "1.18.1", features = ["rt-multi-thread", "macros", "net", "time", "signal"] }
tokio-util = "0.7.1"
url = { version = "2.2.2", features = ["serde"] }
