[package]
name = "stress"
version = "0.1.0"
authors = ["ESRLabs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.44"
clap = { version = "3.1.0", features = ["derive"] }
env_logger = "0.9.0"
futures = "0.3.21"
log = "0.4.14"
northstar = { path = "../../northstar", features = ["api"], default-features = false }
rand = "0.8.5"
tokio = { version = "1.16.1", features = ["rt-multi-thread", "macros", "net", "time", "signal"] }
tokio-util = "0.7.0"
url = { version = "2.2.2", features = ["serde"] }
