[package]
name = "minijail-sys"
version = "0.0.11"
description = "Provides raw (unsafe) bindings to the libminijail C library."
authors = ["The Chromium OS Authors"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
libc = "0.2.44"

[build-dependencies]
cc = "1.0.54"
itertools = "0.9.0"
regex = "1.3.9"
