[package]
name = "inspect"
version = "0.0.1"
authors = ["ESRLabs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
caps = "0.5.4"
nix = { version = "0.25.0", default-features = false, features = [ "process", "user", "signal" ] }
