FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:0.2.4

RUN apt update && apt install --assume-yes libz-dev llvm-dev libclang-dev clang && rm -rf /var/lib/apt/lists/*
ENV BINDGEN_EXTRA_CLANG_ARGS="-I/usr/aarch64-linux-gnu/include"

COPY docker/install-squashfs-tools.sh /
RUN /install-squashfs-tools.sh && rm /install-squashfs-tools.sh
