FROM ghcr.io/cross-rs/aarch64-linux-android:0.2.4

RUN apt-get update && apt-get install --assume-yes --no-install-recommends --fix-missing libclang-dev wget unzip libz-dev && rm -rf /var/lib/apt/lists/*

COPY docker/install-squashfs-tools.sh /
RUN /install-squashfs-tools.sh && rm /install-squashfs-tools.sh
