FROM rustembedded/cross:aarch64-unknown-linux-musl

RUN apt update && apt install --assume-yes squashfs-tools musl-dev libclang-dev
ENV BINDGEN_EXTRA_CLANG_ARGS="-I/usr/local/aarch64-linux-musl/include"
