FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:0.2.4

RUN apt update && apt install --assume-yes libclang-dev libz-dev
ENV BINDGEN_EXTRA_CLANG_ARGS="-I/usr/aarch64-linux-gnu/include"

COPY install-squashfs-tools.sh /
RUN /install-squashfs-tools.sh && rm /install-squashfs-tools.sh