FROM ghcr.io/cross-rs/aarch64-unknown-linux-musl:0.2.4

RUN apt update && apt install --assume-yes musl-dev libclang-dev libz-dev && rm -rf /var/lib/apt/lists/*
ENV BINDGEN_EXTRA_CLANG_ARGS="-I/usr/local/aarch64-linux-musl/include"

COPY docker/install-squashfs-tools.sh /
RUN /install-squashfs-tools.sh && rm /install-squashfs-tools.sh