FROM ghcr.io/cross-rs/aarch64-unknown-linux-musl:edge
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install --assume-yes musl-dev libz-dev llvm-dev libclang-dev clang && rm -rf /var/lib/apt/lists/*

COPY docker/install-squashfs-tools.sh /
RUN /install-squashfs-tools.sh && rm /install-squashfs-tools.sh
