@startuml Update Process
Downloader -> North: Versionlist Request

activate North
North --> Downloader: Versionlist Response
deactivate North
activate Downloader
Downloader -> Downloader: Fetch Updates

Downloader -> North: Download Info
deactivate Downloader
activate North

North -> North: Install Updates
return Update Report

deactivate North
@enduml