[package]
name = "minijail-sys"
version = "0.0.11"
description = "Provides raw (unsafe) bindings to the libminijail C library."
authors = ["The Chromium OS Authors"]
edition = "2018"
build = "build.rs"

[lib]
path = "lib.rs"

[dependencies]
libc = "0.2.81"
libcap-sys = { path = "../../../libcap-sys" }

[build-dependencies]
cc = "1.0.66"
itertools = "0.10.0"
regex = "1.4.2"
