[package]
name = "schema"
version = "0.0.1"
authors = ["ESRLabs"]
edition = "2021"

[dependencies]
anyhow = "1.0.44"
northstar = { path = "../../northstar", features = ["api"], default-features = false }
schemars = "0.8.6"
serde_json = "1.0.68"
structopt = "0.3.25"
