[package]
name = "schema"
version = "0.0.1"
authors = ["ESRLabs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.56"
clap = { version = "3.1.12", features = ["derive"] }
northstar = { path = "../../northstar", features = ["api"], default-features = false }
okapi = "0.7.0-rc.1"
schemars = "0.8.8"
serde_json = "1.0.79"
