[package]
name = "sextant"
version = "0.2.0"
authors = ["ESRLabs"]
edition = "2018"

[dependencies]
anyhow = "1.0"
base64 = "0.13.0"
colored = "2.0"
ed25519-dalek = "1.0"
env_logger = "0.8.3"
log = "0.4.14"
npk = { path = "../../npk" }
structopt = "0.3.21"
tempfile = "3.2"
which = "4.1"
