[package]
name = "sextant"
version = "0.2.0"
authors = ["ESRLabs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.56"
base64 = "0.13.0"
clap = { version = "3.1.12", features = ["derive"] }
colored = "2.0.0"
ed25519-dalek = "1.0.1"
env_logger = "0.9.0"
log = "0.4.16"
northstar = { path = "../../northstar", features = ["npk"] }
tempfile = "3.3.0"
which = "4.2.5"
