[package]
name = "sextant"
version = "0.2.0"
authors = ["ESRLabs"]
edition = "2018"

[dependencies]
anyhow = "1.0"
base64 = "0.13"
colored = "2.0"
ed25519-dalek = "1.0"
env_logger = "0.9"
log = "0.4"
northstar = { path = "../../northstar"}
structopt = "0.3"
tempfile = "3.2"
which = "4.1"
