[package]
name = "sextant"
version = "0.2.0"
authors = ["ESRLabs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.53"
base64 = "0.13.0"
colored = "2.0.0"
ed25519-dalek = "1.0.1"
env_logger = "0.9.0"
log = "0.4.14"
northstar = { path = "../../northstar", features = ["npk"] }
structopt = "0.3.26"
tempfile = "3.3.0"
which = "4.2.2"
