[package]
name = "minijail"
version = "0.1.0"
description = "Provides a safe Rust friendly interface to libminijail."
authors = ["The Chromium OS Authors"]
edition = "2018"

[dependencies]
libc = "0.2.44"

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
minijail-sys = { path = "../minijail-sys" }

[target.'cfg(not(any(target_os = "android", target_os = "linux")))'.dependencies]
anyhow = "1.0.31"
