[package]
name = "test-container"
version = "0.1.0"
authors = ["ESRLabs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.56"
caps = "0.5.3"
clap = { version = "3.1.9", features = ["derive"] }
nix = "0.23.1"
