[package]
name = "test-container"
version = "0.0.1"
authors = ["ESRLabs"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.57"
caps = "0.5.3"
clap = { version = "3.2.2", features = ["derive"] }
nix = { version = "0.24.1", default-features = false, features = ["process", "user"] }
