name: Checks

on: [push, pull_request]

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Cache
        uses: Swatinem/rust-cache@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cargo fmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install libcap
        run: sudo apt install libcap-dev
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
            override: true
      - name: Cache
        uses: Swatinem/rust-cache@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          args: --all-features
