name: Documentation

on:
  push:
   branches:
   - master

jobs:
  doc:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, rust-src

      - name: Build Documentation
        run: cargo doc -p northstar-runtime --all-features --no-deps

      - name: Install OpenApi Generator
        run: |
          curl https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/bin/utils/openapi-generator-cli.sh > openapi-generator-cli
          chmod u+x openapi-generator-cli
          ./openapi-generator-cli version

      - name: Generate manifest jsonschema/html
        run: |
          cargo run --bin schema -- -m manifest -o manifest.json
          ./openapi-generator-cli generate -i manifest.json -g html -o target/doc/manifest

      - name: Generate api jsonschema/html
        run: |
          cargo run --bin schema -- -m api -o api.json
          ./openapi-generator-cli generate -i api.json -g html -o target/doc/api

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          force_orphan: true
