name: Docker
on:
  push:
    tags:
      - docker-*

jobs:
  build:
    name: Build docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-linux-android
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: esrlabs
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: docker/Dockerfile.${{ matrix.target }}
          push: true
          tags: esrlabs/northstar-${{ matrix.target }}:latest
